#!/bin/bash

set -e
set -u

# BASE DE DATOS DE MLFLOW:
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE DATABASE $POSTGRES_DATABASE;
EOSQL

# BASE DE DATOS DE AIRFLOW:
psql -v ON_ERROR_STOP=1  --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER "$POSTGRES_USER_2" PASSWORD '$POSTGRES_PASSWORD_2';
	CREATE DATABASE "$POSTGRES_DATABASE_2";
EOSQL


