# MLFLOW MODEL TRACKING
MLFLOW_ENDPOINT = 'http://mlflow:5000'
MLFLOW_EXPERIMENT = "Clarus_RedWine_experiment"

# METRIC FOR BEST MODEL
METRIC_BM = "r2_validation"
METRIC_BM_TYPE = "max"

# IDS TRUE CONNECTOR INFORMATION
TRUE_CONNECTOR_EDGE_IP = "XXX.XX.XXX.XX"        
TRUE_CONNECTOR_EDGE_PORT = "8889"
TRUE_CONNECTOR_CLOUD_IP = "XXX.XX.XXX.XX"
TRUE_CONNECTOR_CLOUD_PORT = "8084"
